- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          set -x
          set -e

          # Install docker
          apt update -y
          apt install -y docker.io

          # Custom Docker daemon options via drop-in file then restart
          mkdir /etc/systemd/system/docker.service.d
          cat << EOF > /etc/systemd/system/docker.service.d/local-up-cluster.conf
          [Service]
          Environment="DOCKER_OPTS=--iptables=false"
          EOF
          systemctl daemon-reload
          systemctl restart docker

          # Install etcd
          wget https://github.com/coreos/etcd/releases/download/v3.3.0/etcd-v3.3.0-linux-amd64.tar.gz
          tar -zxf etcd-v3.3.0-linux-amd64.tar.gz
          cp etcd-v3.3.0-linux-amd64/etcd{,ctl} /usr/local/bin/

          # Install dependencies
          go get -u github.com/Masterminds/glide

          # Build binaries
          make build
          # Build k8s cmd
          git clone https://github.com/kubernetes/kubernetes ${GOPATH}/src/k8s.io/kubernetes
          make -C ${GOPATH}/src/k8s.io/kubernetes WHAT="cmd/kubectl cmd/hyperkube"

          # Stopping firewall and allow all traffic
          iptables -F
          iptables -X
          iptables -t nat -F
          iptables -t nat -X
          iptables -t mangle -F
          iptables -t mangle -X
          iptables -P INPUT ACCEPT
          iptables -P FORWARD ACCEPT
          iptables -P OUTPUT ACCEPT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
